# Generated by Django 4.1.7 on 2023-06-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArtistData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.CharField(max_length=20)),
                ("impression", models.PositiveIntegerField()),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("conversions", models.DecimalField(decimal_places=2, max_digits=10)),
                ("bookings", models.PositiveIntegerField()),
            ],
        ),
    ]
