# Generated by Django 4.1.7 on 2023-06-15 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Bookings", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MetaData",
            new_name="BookingsData",
        ),
    ]
