# Generated by Django 4.1.7 on 2023-06-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bookings", "0002_rename_metadata_bookingsdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtistBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("per_day", models.DateField()),
                ("time", models.TimeField()),
                ("customer_name", models.CharField(max_length=255)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("artist_name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("service_name", models.CharField(max_length=255)),
                ("discount_used", models.BooleanField(default=False)),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Complete", "Complete"),
                            ("Cancel", "Cancel"),
                            ("Pending", "Pending"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="BookingsData",
        ),
    ]
