# Generated by Django 4.1.7 on 2023-06-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bookings", "0003_artistbooking_delete_bookingsdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artistbooking",
            name="per_day",
            field=models.IntegerField(),
        ),
    ]
