from django.db import models

class DailyStats(models.Model):
    date = models.CharField(max_length=50)
    clicks = models.CharField(max_length=50)
    cost = models.CharField(max_length=50)
    conversions = models.CharField(max_length=50)
    cost_per_conversion = models.CharField(max_length=50)
    search_word = models.CharField(max_length=50)
    search_word_clicks = models.CharField(max_length=50)
    search_word_impressions = models.CharField(max_length=50)
    search_word_cost = models.CharField(max_length=50)
    search_salon = models.CharField(max_length=50)
    search_salon_clicks = models.CharField(max_length=50)
    search_salon_impressions = models.CharField(max_length=50)
    search_salon_cost = models.CharField(max_length=50)
    search_keyword = models.CharField(max_length=50)
    search_keyword_clicks = models.CharField(max_length=50)
    search_keyword_ctr = models.CharField(max_length=50)
    campaign_name = models.CharField(max_length=50)
    optimization_score = models.CharField(max_length=50)
    network_name = models.CharField(max_length=50)
    network_clicks = models.CharField(max_length=50)
    network_cost = models.CharField(max_length=50)
    device_name = models.CharField(max_length=50)
    device_cost = models.CharField(max_length=50)
    device_clicks = models.CharField(max_length=50)
    device_conversion = models.CharField(max_length=50)
    gender = models.CharField(max_length=50)
    age_range = models.CharField(max_length=50)
    gender_impression = models.CharField(max_length=50)
    per_hour = models.CharField(max_length=50)
    per_hour_impression = models.CharField(max_length=50)
    per_day = models.CharField(max_length=50)
    per_day_per_hour = models.CharField(max_length=50)
    per_day_per_hour_impression = models.CharField(max_length=50)
    campaigns_cost = models.CharField(max_length=50)
    campaigns_conversion = models.CharField(max_length=50)
    campaigns_cost_per_conversion = models.CharField(max_length=50)

    def __str__(self):
        return self.date
